#!/usr/bin/env python3
"""
Render Setup Helper Script
This script helps users configure the PawParties system for Render deployment
"""

import json
import os
import sys
from typing import Optional


def print_header(title: str):
    """Print a formatted header"""
    print("\n" + "=" * 60)
    print(title.center(60))
    print("=" * 60)


def print_step(step: int, description: str):
    """Print a numbered step"""
    print(f"\n[Step {step}] {description}")
    print("-" * 40)


def get_input(prompt: str, required: bool = True, password: bool = False) -> str:
    """Get user input with validation"""
    while True:
        if password:
            import getpass

            value = getpass.getpass(prompt + ": ").strip()
        else:
            value = input(prompt + ": ").strip()

        if value or not required:
            return value
        print("❌ This field is required. Please try again.")


def save_env_file(env_vars: dict):
    """Save environment variables to .env file"""
    env_file = ".env"

    # Read existing .env if it exists
    existing_vars = {}
    if os.path.exists(env_file):
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    existing_vars[key] = value

    # Update with new vars
    existing_vars.update(env_vars)

    # Write back to file
    with open(env_file, "w") as f:
        f.write("# PawParties Environment Configuration\n")
        f.write("# Generated by setup_render.py\n\n")

        # Group variables by category
        categories = {
            "Application": ["SECRET_KEY"],
            "Pinata IPFS": ["PINATA_API_KEY", "PINATA_SECRET_KEY"],
            "Render API": ["RENDER_API_KEY", "RENDER_SERVICE_ID"],
            "GitHub Gist": ["GITHUB_TOKEN", "GITHUB_GIST_ID"],
            "AI Chatbot": ["GEMINI_API_KEY"],
            "Manual Recovery": ["PINATA_RESTORE_CID"],
        }

        for category, keys in categories.items():
            category_vars = {k: v for k, v in existing_vars.items() if k in keys}
            if category_vars:
                f.write(f"# {category}\n")
                for key, value in category_vars.items():
                    f.write(f"{key}={value}\n")
                f.write("\n")

        # Write any remaining vars
        remaining = {
            k: v
            for k, v in existing_vars.items()
            if k not in sum(categories.values(), [])
        }
        if remaining:
            f.write("# Other\n")
            for key, value in remaining.items():
                f.write(f"{key}={value}\n")

    print(f"\n✅ Environment variables saved to {env_file}")


def generate_secret_key() -> str:
    """Generate a secure secret key"""
    import secrets

    return secrets.token_hex(32)


def main():
    print_header("PAWPARTIES RENDER SETUP HELPER")
    print("\nThis script will help you configure PawParties for Render deployment")
    print("It will create/update a .env file with the necessary environment variables")

    env_vars = {}

    # Step 1: Application Secret Key
    print_step(1, "Application Secret Key")
    print("This is used for session encryption and security.")
    use_generated = input("Generate a random secret key? (recommended) [Y/n]: ").lower()
    if use_generated != "n":
        env_vars["SECRET_KEY"] = generate_secret_key()
        print("✅ Generated secure secret key")
    else:
        env_vars["SECRET_KEY"] = get_input("Enter your secret key", password=True)

    # Step 2: Pinata Configuration (Required)
    print_step(2, "Pinata IPFS Configuration (REQUIRED)")
    print("Sign up for free at: https://pinata.cloud")
    print("Go to API Keys section and create a new key with:")
    print("  - pinFileToIPFS permission")
    print("  - pinList permission")
    print("  - hashMetadata permission")

    env_vars["PINATA_API_KEY"] = get_input("Enter Pinata API Key")
    env_vars["PINATA_SECRET_KEY"] = get_input("Enter Pinata Secret Key", password=True)

    # Step 3: Render API Configuration (Recommended)
    print_step(3, "Render API Configuration (RECOMMENDED)")
    print("This allows automatic environment variable updates for CID persistence.")
    print("1. Go to Render Dashboard → Account Settings → API Keys")
    print("2. Create a new API key")
    print("3. Get your service ID from the service URL (e.g., srv-xxxxx)")

    configure_render = input("Configure Render API? [Y/n]: ").lower()
    if configure_render != "n":
        env_vars["RENDER_API_KEY"] = get_input("Enter Render API Key")
        env_vars["RENDER_SERVICE_ID"] = get_input("Enter Render Service ID")
    else:
        print("⚠️  Skipping Render API (CID persistence may be less reliable)")

    # Step 4: GitHub Gist Configuration (Optional)
    print_step(4, "GitHub Gist Configuration (OPTIONAL)")
    print("This provides an additional backup method for CID storage.")
    print("1. Go to GitHub Settings → Developer Settings → Personal Access Tokens")
    print("2. Generate a token with 'gist' scope")
    print("3. Create a new Gist and copy its ID from the URL")

    configure_gist = input("Configure GitHub Gist backup? [y/N]: ").lower()
    if configure_gist == "y":
        env_vars["GITHUB_TOKEN"] = get_input(
            "Enter GitHub Personal Access Token", password=True
        )
        env_vars["GITHUB_GIST_ID"] = get_input("Enter Gist ID")
    else:
        print("⚠️  Skipping GitHub Gist backup")

    # Step 5: AI Chatbot (Optional)
    print_step(5, "AI Chatbot Configuration (OPTIONAL)")
    print("Configure Google Gemini for AI-powered chatbot.")
    print("Get API key from: https://makersuite.google.com/app/apikey")

    configure_gemini = input("Configure Gemini AI? [y/N]: ").lower()
    if configure_gemini == "y":
        env_vars["GEMINI_API_KEY"] = get_input("Enter Gemini API Key", password=True)
    else:
        print("⚠️  Skipping AI chatbot (will use rule-based responses)")

    # Step 6: Manual Recovery CID (Optional)
    print_step(6, "Manual Recovery CID (OPTIONAL)")
    print("If you have a previous backup CID, you can set it for recovery.")

    has_cid = input("Do you have a previous backup CID? [y/N]: ").lower()
    if has_cid == "y":
        env_vars["PINATA_RESTORE_CID"] = get_input("Enter IPFS CID")

    # Save configuration
    print_header("SAVING CONFIGURATION")
    save_env_file(env_vars)

    # Generate render.yaml if it doesn't exist
    if not os.path.exists("render.yaml"):
        print("\n📝 Creating render.yaml...")
        render_config = {
            "services": [
                {
                    "type": "web",
                    "name": "pawparties-app",
                    "env": "python",
                    "region": "oregon",
                    "plan": "free",
                    "runtime": "python",
                    "buildCommand": "pip install -r requirements.txt",
                    "startCommand": "python scripts/render_startup.py && gunicorn app:app --bind 0.0.0.0:$PORT",
                    "healthCheckPath": "/",
                    "envVars": [{"key": k, "sync": False} for k in env_vars.keys()],
                    "autoDeploy": True,
                }
            ]
        }

        import yaml

        try:
            with open("render.yaml", "w") as f:
                yaml.dump(render_config, f, default_flow_style=False, sort_keys=False)
            print("✅ Created render.yaml")
        except ImportError:
            print("⚠️  PyYAML not installed. Please create render.yaml manually.")

    # Print deployment instructions
    print_header("DEPLOYMENT INSTRUCTIONS")
    print("""
1. Commit your changes:
   git add .
   git commit -m "Configure PawParties for Render deployment"
   git push origin main

2. Deploy to Render:
   - Go to https://render.com
   - Create a new Web Service
   - Connect your GitHub repository
   - Select the branch to deploy
   - Click "Create Web Service"

3. Set Environment Variables in Render:
   - Go to your service dashboard
   - Navigate to "Environment" tab
   - Add the variables from .env file
   - Save changes

4. Monitor Deployment:
   - Check the "Logs" tab for deployment progress
   - Look for "STARTUP RESTORE COMPLETED SUCCESSFULLY"
   - Verify blockchain restoration status

5. Test the Application:
   - Visit your Render URL
   - Login with default credentials:
     Admin: admin/admin123
     Officer: officer1/officer123
   - Change passwords immediately!
    """)

    print_header("CONFIGURATION COMPLETE")
    print("\n✅ Your PawParties system is configured for Render deployment!")
    print("📋 Environment variables saved to .env")
    print("🚀 Follow the deployment instructions above to deploy to Render")

    # Check configuration strength
    print("\n📊 Configuration Strength:")
    strength = 0
    max_strength = 4

    if "PINATA_API_KEY" in env_vars:
        print("  ✅ Pinata IPFS configured (Required)")
        strength += 1
    else:
        print("  ❌ Pinata IPFS not configured")

    if "RENDER_API_KEY" in env_vars:
        print("  ✅ Render API configured (Recommended)")
        strength += 1
    else:
        print("  ⚠️  Render API not configured")

    if "GITHUB_TOKEN" in env_vars:
        print("  ✅ GitHub Gist backup configured (Optional)")
        strength += 1
    else:
        print("  ℹ️  GitHub Gist backup not configured")

    if "GEMINI_API_KEY" in env_vars:
        print("  ✅ AI Chatbot configured (Optional)")
        strength += 1
    else:
        print("  ℹ️  AI Chatbot not configured")

    print(f"\nConfiguration Score: {strength}/{max_strength}")

    if strength < 2:
        print("⚠️  WARNING: Your configuration may not provide reliable persistence.")
        print("   Consider adding Render API or GitHub Gist backup.")
    else:
        print("✅ Your configuration provides good redundancy for data persistence.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {str(e)}")
        sys.exit(1)
